name: deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔄
        uses: actions/checkout@v3

      - name: Setup Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install Dependencies 📦
        run: |
          gem install bundler
          bundle install

      - name: Build Site 🏗️
        run: |
          export JEKYLL_ENV=production
          bundle exec jekyll build

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
